import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportAttendanceToExcel = (
  attendance: any[]
) => {
  const rows = attendance.map((item) => ({
    Employee:
      `${item.employee.firstName} ${item.employee.lastName}`,

    Department:
      item.employee.department?.name,

    Designation:
      item.employee.designation,

    CheckIn: item.checkIn
      ? new Date(
          item.checkIn
        ).toLocaleTimeString()
      : "--",

    CheckOut: item.checkOut
      ? new Date(
          item.checkOut
        ).toLocaleTimeString()
      : "--",

    WorkingHours:
      item.workingHours ?? "--",

    Status: item.status,
  }));

  const worksheet =
    XLSX.utils.json_to_sheet(rows);

  worksheet["!cols"] = [
    { wch: 28 },
    { wch: 22 },
    { wch: 22 },
    { wch: 18 },
    { wch: 18 },
    { wch: 15 },
    { wch: 15 },
  ];

  const workbook =
    XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    "Attendance Report"
  );

  XLSX.writeFile(
    workbook,
    `Attendance_Report_${
      new Date()
        .toISOString()
        .split("T")[0]
    }.xlsx`
  );
};

export const exportAttendanceToPDF = (
  attendance: any[]
) => {
  const doc = new jsPDF();

  const today = new Date();

  doc.setFontSize(20);
  doc.setTextColor(25, 118, 210);
  doc.text(
    "Employee Management System",
    14,
    18
  );

  doc.setFontSize(16);
  doc.setTextColor(0);

  doc.text(
    "Attendance Report",
    14,
    30
  );

  doc.setFontSize(11);

  doc.text(
    `Generated: ${today.toLocaleString()}`,
    14,
    38
  );

  doc.text(
    `Total Employees: ${attendance.length}`,
    14,
    45
  );

  autoTable(doc, {
    startY: 55,

    head: [[
      "Employee",
      "Department",
      "Designation",
      "Check In",
      "Check Out",
      "Hours",
      "Status",
    ]],

    body: attendance.map((item) => [
      `${item.employee.firstName} ${item.employee.lastName}`,
      item.employee.department?.name,
      item.employee.designation,
      item.checkIn
        ? new Date(
            item.checkIn
          ).toLocaleTimeString()
        : "--",
      item.checkOut
        ? new Date(
            item.checkOut
          ).toLocaleTimeString()
        : "--",
      item.workingHours ?? "--",
      item.status,
    ]),

    headStyles: {
      fillColor: [25, 118, 210],
      textColor: 255,
      halign: "center",
    },

    styles: {
      fontSize: 10,
      cellPadding: 3,
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },

    didDrawPage: (data) => {
      const pageCount =
        doc.getNumberOfPages();

      doc.setFontSize(10);

      doc.text(
        `Page ${pageCount}`,
        data.settings.margin.left,
        doc.internal.pageSize.height - 10
      );

      doc.text(
        "Generated by Employee Management System",
        doc.internal.pageSize.width - 90,
        doc.internal.pageSize.height - 10
      );
    },
  });

  doc.save(
    `Attendance_Report_${
      new Date()
        .toISOString()
        .split("T")[0]
    }.pdf`
  );
};